apiVersion: v1
kind: Service
metadata:
  name: kube-flask-service
spec:
  selector:
    app: kube-flask
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-flask
spec:
  selector:
    matchLabels:
      app: kube-flask
  replicas: 3
  template:
    metadata:
      labels:
        app: kube-flask
    spec:
      containers:
      - name: kubernetes-flask
        image: kubernetes-flask
        imagePullPolicy: Never
        ports:
        - containerPort: 8080